# Generated by Django 4.1.2 on 2022-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('education', models.CharField(blank=True, max_length=250, null=True)),
                ('profession', models.CharField(blank=True, max_length=250, null=True)),
                ('graduated', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
